language: node_js
before_install:
- ./scripts/ensure-compatible-npm.sh
script: travis_retry npm test
node_js:
- 'iojs'
- '0.12'
- '0.11'
- '0.10'
- '0.8'
sudo: false
notifications:
  on_success: change
  on_failure: always